<?php

declare(strict_types=1);

/**
 * 告警指标字典 —— docs/alarm/metrics.md §1 的机器可读副本（共 28 个：CVM 10 / WEB 8 / CLB 4 / MYSQL 6）。
 *
 * 唯一来源是 metrics.md。禁止在此处单独增删指标而不改 metrics.md ——
 * 契约 §2.7 规定本文件是 GET /api/alarm/metrics 的唯一数据源。
 *
 * 唯一键 = namespace + "." + metricName。指标属系统元数据而非租户数据，**不入库**（metrics.md §5）。
 */

return [
    [
        'namespace' => 'CVM',
        'metricName' => 'CpuUtilizationRate',
        'metricNameCn' => 'CPU 使用率',
        'unit' => '%',
        'policyType' => [2],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 80,
        'suggestedContinuity' => 3,
        'description' => '统计周期内实例 CPU 使用率平均值，取值 0-100。持续偏高通常意味着计算资源打满、需扩容或存在死循环。',
    ],
    [
        'namespace' => 'CVM',
        'metricName' => 'MemoryUsageRate',
        'metricNameCn' => '内存使用率',
        'unit' => '%',
        'policyType' => [2],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 90,
        'suggestedContinuity' => 3,
        'description' => '统计周期内实例已用内存占物理内存比例，取值 0-100。接近 100% 时进程易被 OOM Killer 终止。',
    ],
    [
        'namespace' => 'CVM',
        'metricName' => 'DiskUsageRate',
        'metricNameCn' => '磁盘使用率',
        'unit' => '%',
        'policyType' => [2],
        'periodOptions' => [30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 85,
        'suggestedContinuity' => 2,
        'description' => '已用磁盘容量占分区总容量比例，取值 0-100。属慢变量，仅提供 30/60 分钟粒度。写满会导致服务不可写。',
    ],
    [
        'namespace' => 'CVM',
        'metricName' => 'LanInTraffic',
        'metricNameCn' => '网络入带宽',
        'unit' => 'Mbps',
        'policyType' => [2],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 500,
        'suggestedContinuity' => 3,
        'description' => '统计周期内网卡平均入方向带宽。持续超限通常触发限流或丢包。',
    ],
    [
        'namespace' => 'CVM',
        'metricName' => 'LanOutTraffic',
        'metricNameCn' => '网络出带宽',
        'unit' => 'Mbps',
        'policyType' => [2],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 500,
        'suggestedContinuity' => 3,
        'description' => '统计周期内网卡平均出方向带宽。超限常伴随出口链路拥塞。',
    ],
    [
        'namespace' => 'CVM',
        'metricName' => 'DiskReadTraffic',
        'metricNameCn' => '磁盘读吞吐',
        'unit' => 'MB/s',
        'policyType' => [2],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 100,
        'suggestedContinuity' => 3,
        'description' => '统计周期内云盘平均读吞吐。持续偏高可能是缓存失效或全表扫描。',
    ],
    [
        'namespace' => 'CVM',
        'metricName' => 'DiskWriteTraffic',
        'metricNameCn' => '磁盘写吞吐',
        'unit' => 'MB/s',
        'policyType' => [2],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 100,
        'suggestedContinuity' => 3,
        'description' => '统计周期内云盘平均写吞吐。持续偏高需关注磁盘寿命与写入瓶颈。',
    ],
    [
        'namespace' => 'CVM',
        'metricName' => 'DiskIoUtilization',
        'metricNameCn' => '磁盘 IO 使用率',
        'unit' => '%',
        'policyType' => [2],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 85,
        'suggestedContinuity' => 3,
        'description' => '磁盘忙碌时间占比，取值 0-100。长期 >85% 会显著抬高业务延迟。',
    ],
    [
        'namespace' => 'CVM',
        'metricName' => 'TcpCurrEstab',
        'metricNameCn' => 'TCP 连接数',
        'unit' => '个',
        'policyType' => [2],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 5000,
        'suggestedContinuity' => 3,
        'description' => '统计周期内平均处于 ESTABLISHED 状态的 TCP 连接数。持续增长需排查连接泄漏。',
    ],
    [
        'namespace' => 'CVM',
        'metricName' => 'LoadAverage1m',
        'metricNameCn' => '一分钟平均负载',
        'unit' => '无',
        'policyType' => [2],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 8,
        'suggestedContinuity' => 3,
        'description' => '一分钟平均负载（Linux loadavg）。经验阈值约为 vCPU 核数，需按实例规格调整。',
    ],
    [
        'namespace' => 'WEB',
        'metricName' => 'HttpRequestCount',
        'metricNameCn' => '请求数（QPS）',
        'unit' => '次/秒',
        'policyType' => [1],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 10000,
        'suggestedContinuity' => 3,
        'description' => '统计周期内平均每秒请求数（QPS）。持续突增需确认是否流量异常或压测。',
    ],
    [
        'namespace' => 'WEB',
        'metricName' => 'Http4xxCount',
        'metricNameCn' => 'HTTP 4xx 错误数',
        'unit' => '次',
        'policyType' => [1],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 100,
        'suggestedContinuity' => 2,
        'description' => '统计周期内 4xx 响应数量。4xx 多为客户端参数/鉴权问题，不一定需值班介入。',
    ],
    [
        'namespace' => 'WEB',
        'metricName' => 'Http5xxCount',
        'metricNameCn' => 'HTTP 5xx 错误数',
        'unit' => '次',
        'policyType' => [1],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 10,
        'suggestedContinuity' => 2,
        'description' => '统计周期内 5xx 响应数量。非零即代表服务端异常，量级越大越紧急。',
    ],
    [
        'namespace' => 'WEB',
        'metricName' => 'Http5xxRatio',
        'metricNameCn' => '5xx 错误率',
        'unit' => '%',
        'policyType' => [1],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 5,
        'suggestedContinuity' => 3,
        'description' => '5xx 请求数 / 总请求数 × 100，取值 0-100。比率比绝对值更抗流量波动影响。',
    ],
    [
        'namespace' => 'WEB',
        'metricName' => 'HttpAvgDuration',
        'metricNameCn' => '平均响应延迟',
        'unit' => 'ms',
        'policyType' => [1],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 500,
        'suggestedContinuity' => 3,
        'description' => '统计周期内全量请求的平均响应耗时。平均值会掩盖长尾，需与 P99 搭配。',
    ],
    [
        'namespace' => 'WEB',
        'metricName' => 'HttpP99Duration',
        'metricNameCn' => 'P99 响应延迟',
        'unit' => 'ms',
        'policyType' => [1],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 1000,
        'suggestedContinuity' => 5,
        'description' => '统计周期内响应耗时 99 分位值。更早暴露长尾劣化，建议作为对外 SLA 主指标。',
    ],
    [
        'namespace' => 'WEB',
        'metricName' => 'HttpTimeoutCount',
        'metricNameCn' => '超时请求数',
        'unit' => '次',
        'policyType' => [1],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 5,
        'suggestedContinuity' => 2,
        'description' => '统计周期内客户端/网关判定超时的请求数量。反映链路最差表现。',
    ],
    [
        'namespace' => 'WEB',
        'metricName' => 'HttpSuccessRate',
        'metricNameCn' => '服务成功率',
        'unit' => '%',
        'policyType' => [1],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '<',
        'defaultThreshold' => 99,
        'suggestedContinuity' => 3,
        'description' => '非 5xx 且未超时的请求占比，取值 0-100。作为 SLA 视角的补充指标。',
    ],
    [
        'namespace' => 'CLB',
        'metricName' => 'ClbBackendUnhealthyCount',
        'metricNameCn' => '后端异常数',
        'unit' => '个',
        'policyType' => [3],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 1,
        'suggestedContinuity' => 2,
        'description' => '统计周期内健康检查判定为异常的后端 RS 数量。非零即已影响可用性。',
    ],
    [
        'namespace' => 'CLB',
        'metricName' => 'ClbHttp5xxRatio',
        'metricNameCn' => '5xx 比例',
        'unit' => '%',
        'policyType' => [3],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 5,
        'suggestedContinuity' => 3,
        'description' => 'CLB 侧转发的 5xx 响应占比，取值 0-100。与后端 `WEB.Http5xxRatio` 可交叉定位问题在 LB 还是后端。',
    ],
    [
        'namespace' => 'CLB',
        'metricName' => 'ClbActiveConnections',
        'metricNameCn' => '活跃连接数',
        'unit' => '个',
        'policyType' => [3],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 10000,
        'suggestedContinuity' => 3,
        'description' => '统计周期内 CLB 活跃连接数。接近实例规格上限会触发限流。',
    ],
    [
        'namespace' => 'CLB',
        'metricName' => 'ClbQps',
        'metricNameCn' => '请求数',
        'unit' => '次/秒',
        'policyType' => [3],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 20000,
        'suggestedContinuity' => 3,
        'description' => '统计周期内 CLB 平均每秒转发请求数。用于判断是否触及带宽/QPS 配额。',
    ],
    [
        'namespace' => 'MYSQL',
        'metricName' => 'MysqlCpuUsageRate',
        'metricNameCn' => 'MySQL CPU 使用率',
        'unit' => '%',
        'policyType' => [4],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 80,
        'suggestedContinuity' => 3,
        'description' => 'MySQL 实例 CPU 使用率，取值 0-100。持续偏高需排查慢 SQL 或缺少索引。',
    ],
    [
        'namespace' => 'MYSQL',
        'metricName' => 'MysqlSlowQueryCount',
        'metricNameCn' => '慢查询数',
        'unit' => '次',
        'policyType' => [4],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 10,
        'suggestedContinuity' => 2,
        'description' => '统计周期内超过 `long_query_time` 的查询条数。激增通常伴随锁等待或全表扫描。',
    ],
    [
        'namespace' => 'MYSQL',
        'metricName' => 'MysqlConnectionCount',
        'metricNameCn' => '连接数',
        'unit' => '个',
        'policyType' => [4],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 1000,
        'suggestedContinuity' => 3,
        'description' => '当前活跃连接数。需结合实例规格调整，接近 `max_connections` 会导致连接被拒。',
    ],
    [
        'namespace' => 'MYSQL',
        'metricName' => 'MysqlConnectionRatio',
        'metricNameCn' => '连接数使用率',
        'unit' => '%',
        'policyType' => [4],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 80,
        'suggestedContinuity' => 3,
        'description' => '当前连接数 / `max_connections` × 100。百分比口径比绝对值更可移植。',
    ],
    [
        'namespace' => 'MYSQL',
        'metricName' => 'MysqlReplicationDelay',
        'metricNameCn' => '主从延迟',
        'unit' => '秒',
        'policyType' => [4],
        'periodOptions' => [1, 5, 10, 30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 30,
        'suggestedContinuity' => 2,
        'description' => '主从复制秒级延迟。持续升高会导致读到旧数据，通常指向大事务或主库 IO 瓶颈。',
    ],
    [
        'namespace' => 'MYSQL',
        'metricName' => 'MysqlDiskUsageRate',
        'metricNameCn' => '磁盘使用率',
        'unit' => '%',
        'policyType' => [4],
        'periodOptions' => [30, 60],
        'defaultOperator' => '>',
        'defaultThreshold' => 85,
        'suggestedContinuity' => 2,
        'description' => '实例磁盘已用容量占比，取值 0-100。慢变量，仅 30/60 分钟粒度。写满会导致实例只读。',
    ],
];
